/* eslint-disable */
/** Auto-generated by scripts/import-parametric-zones.mjs — parametric zone map */
import type { ZoneId } from './types';

export interface SnappedZonePaths {
  paths: string[];
  fillRule?: 'evenodd' | 'nonzero';
}

export const SNAPPED_ZONE_PATHS: Record<ZoneId, SnappedZonePaths> = {
  'zone-6': {
    paths: [
      "M 1334 140 C 1433 140 1514 164 1514 193 C 1514 222 1433 246 1334 246 C 1235 246 1154 222 1154 193 C 1154 164 1235 140 1334 140 Z",
    ],
  },
  'zone-5': {
    paths: [
      "M 931 314 L 1010 226 Q 1154 116 1334 103 Q 1514 116 1658 226 L 1737 314 Q 1334 326 931 314 Z M 1334 140 C 1433 140 1514 164 1514 193 C 1514 222 1433 246 1334 246 C 1235 246 1154 222 1154 193 C 1154 164 1235 140 1334 140 Z",
    ],
    fillRule: 'evenodd' as const,
  },
  'zone-4': {
    paths: [
      "M 876 492 Q 928 494 1016 516 C 1016 467 1158 427 1334 427 C 1510 427 1652 467 1652 516 Q 1740 494 1792 492 Q 1782 439 1771 386 Q 1753 350 1735 314 Q 1334 314 933 314 Q 915 350 897 386 Q 887 439 876 492 Z",
    ],
  },
  'zone-3': {
    paths: [
      "M 1334 427 C 1510 427 1652 467 1652 516 C 1652 565 1510 605 1334 605 C 1158 605 1016 565 1016 516 C 1016 467 1158 427 1334 427 Z",
    ],
  },
  'zone-2': {
    paths: [
      "M 868 532 L 863 601 Q 1334 939 1805 601 L 1792 492 Q 1740 494 1652 516 C 1652 565 1510 605 1334 605 C 1158 605 1016 565 1016 516 Q 928 494 876 492 L 868 532 Z",
    ],
  },
  'zone-1': {
    paths: [
      "M 863 601 Q 972 663 1081 724 Q 985 749 889 774 L 863 601 Z",
      "M 1805 601 Q 1696 663 1587 724 Q 1683 749 1779 774 L 1805 601 Z",
    ],
  },
};

export const SNAPPED_LABEL_POSITIONS: Record<ZoneId, { x: number; y: number }[]> = {
  'zone-6': [{ x: 1334, y: 193 }],
  'zone-5': [{ x: 1145, y: 281 }, { x: 1523, y: 281 }],
  'zone-4': [{ x: 1111, y: 371 }, { x: 1557, y: 371 }],
  'zone-3': [{ x: 1334, y: 516 }],
  'zone-2': [{ x: 1128, y: 678 }, { x: 1540, y: 678 }],
  'zone-1': [{ x: 944, y: 700 }, { x: 1724, y: 700 }],
};

export const ZONE_STROKE_OVERLAYS: Partial<Record<ZoneId, string[]>> = {
  'zone-6': [
      "M 1334 140 C 1433 140 1514 164 1514 193 C 1514 222 1433 246 1334 246 C 1235 246 1154 222 1154 193 C 1154 164 1235 140 1334 140 Z",
  ],
  'zone-5': [
      "M 931 314 L 1010 226 Q 1154 116 1334 103 Q 1514 116 1658 226 L 1737 314",
  ],
  'zone-4': [
      "M 876 492 Q 928 494 1016 516",
      "M 1016 516 C 1016 467 1158 427 1334 427 C 1510 427 1652 467 1652 516 Q 1740 494 1792 492 Q 1782 439 1771 386 Q 1753 350 1735 314 Q 1334 314 933 314 Q 915 350 897 386 Q 887 439 876 492",
  ],
  'zone-2': [
      "M 868 532 L 863 601 Q 1334 939 1805 601 L 1792 492M 1652 516 C 1652 565 1510 605 1334 605 C 1158 605 1016 565 1016 516 M 876 492 L 868 532",
  ],
};

export const SNAP_GENERATION_META = {
  generatedAt: '2026-06-06T14:57:34.423Z',
  source: 'zones-parametric.json',
  smoothed: false,
  parametric: true,
  maxEdgeErrorPx: 0,
  totalSnappedPoints: 0,
} as const;
